apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app
          image: us-central1-docker.pkg.dev/matsyaonline/matsya-container-repo-dev/matsya-capital-fe:v1
          ports:
            - containerPort: 80


---
apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  type: LoadBalancer
  loadBalancerIP: 34.29.202.44
  ports:
    - port: 80
  selector:
    app: my-app
